### ISSUE TITLE
Improve contract code

### ISSUE THREAD

**Issue by sembrestels** [P2PModels/committees#13]
- [x] Remove `Increment` and `Decrement` events, and the `value` public variable.
- [x] Only emit `name`, `description`, `tokenManager`, and `voting` on `CreateCommittee` event. The rest can be requested to the blockchain later. See #12.
- [x] Remove `votingType` and `committeeType` from the `createCommittee` function and the Committee struct too. We can know what kind of committe and voting it is looking at the TokenManager and Voting app public variables in the script.js (see #12).
- [x] Use a constant to manage the error "The committee doesn't exist" (similar to how it is done in `BaseTemplate`).

**Comment by PJColombo** [comment]
- [x] Add modifiers
