### ISSUE TITLE
Refactor frontend

### ISSUE THREAD

**Issue by sembrestels** [P2PModels/committees#7]
- [x] Refactor part of the frontend structure, using the new AragonDS and the mockups in #3.
- [x] Implement a better validation logic in some components and improve their aesthetics.
- [x] Use the `IdentityProvider` in the whole app as in [Voting](https://github.com/aragon/aragon-apps/blob/master/apps/voting/app/src/identity-manager.js), and use `LocalIdentitiesAutoComplete` as in [TokenManager](https://github.com/aragon/aragon-apps/blob/4d9d13873647b87058e4d8b949df4cb3b49ef275/apps/token-manager/app/src/components/Panels/TokenPanelContent.js#L180-L186).

**Comment by PJColombo** [comment]
- [x] Fix SidePanel component close animation problem.
- [x] Refactor sidepanel management logic
- [ ] Memoize screen components.
- [x] Refactor screen components.
- [x] Refactor member list component
- [x] Refactor sidepanel components. 
- [x] Connect contract functions to frontend
- [x] Restructure components directory tree

**Comment by sembrestels** [comment]
The frontend refactoring has been accomplished. Closing in favor of #20.
